🌱: Add samples of react-native-vector-icons
ws-4020/rn-spoiler pull request #22
Opened 2020-10-16 05:20 UTC by Takumon

## やったこと

- [ ] Impl a basic component of react-native-vector-icons
- [ ] Impl a sample component of icons in App.tsx
- [ ] Add local icons according to the rule of react-native-vector-icons.
- [ ] Impl a sample component of local icon in App.tsx

## やっていないこと

Nothing

## 動作確認

- [ ] Launch an app and view a top page.

## デバイス

- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## その他（レビュアーへの申し送り事項、懸念点など）

Nothing

2020-10-16 06:50 UTC, in-a-paddy commented on src/App.tsx
> +      <CameraIcon size={30} color="#9D8CB8" />
Colors must not be hard coded, and basics should be implemented as specific as possible, I think.

For example, avoid implementing `Button` and using it with `color={Colors.confirm}` or `color={Colors.background}`, but should implement each buttons as `ConfirmButton`, `CloseButton`.

2020-10-16 06:50 UTC, in-a-paddy commented on src/App.tsx
> +      <CameraIcon size={30} color="#9D8CB8" />
I'm not so sure, I think the size should be determined by the layout, not by the icon itself.

2020-10-19 01:40 UTC, Takumon commented on src/App.tsx
> +      <CameraIcon size={30} color="#9D8CB8" />
I added default value of color attribute in CameraIcon.

2020-10-19 01:43 UTC, Takumon commented on src/App.tsx
> +      <CameraIcon size={30} color="#9D8CB8" />
I added default value of size which equals default text size of react-native-elements.

2020-10-19 06:45 UTC, Takumon commented on src/example/components/basics/CameraIcon.tsx
> +const CameraIcon = ({size = 26, color='#9D8CB8',  ...props}: SpecificIconType) => {
fix lint

2020-10-19 06:46 UTC, Takumon commented on src/example/components/basics/TrashIcon.tsx
> +const TrashIcon = ({size = 26, color='#9D8CB8', ...props}: SpecificIconType) => {
fix lint

2020-10-19 06:46 UTC, Takumon commented on src/example/components/basics/GuruGuruIcon.tsx
> +const GuruGuruIcon = ({size = 26, color='#9D8CB8', ...props}: Props) => {
fix lint

2020-10-19 06:46 UTC, Takumon commented on src/example/components/basics/TrashIcon.tsx
> +  return <Icon name='trash' type='font-awesome' color={color} size={size} {...props} />;
fix lint

2020-10-19 06:46 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +import {StyleSheet, View} from 'react-native';
fix lint

2020-10-19 06:46 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +import {StyleSheet, View} from 'react-native';
fix lint

2020-10-19 06:47 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +const textFontSize = 16
fix lint

2020-10-19 06:47 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +      <Text style={styles.text}>Sample text 1 <CameraIcon size={textFontSize} /></Text>
fix lint

2020-10-19 06:47 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +  }
fix lint

2020-10-19 06:47 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +      <Text style={styles.text}><GuruGuruIcon size={textFontSize} /> Sample text 2 <TrashIcon size={textFontSize} /></Text>
fix lint

2020-10-19 08:59 UTC, in-a-paddy requested changes

2020-10-19 08:59 UTC, in-a-paddy commented on .eslintignore
> +src/generated/*
Add it to `ignorePatterns` in `.eslintrc.js` (I don't want to put it in the root directory).

2020-10-19 08:59 UTC, in-a-paddy commented on .eslintignore
> +svgr-template.js
You don't have to ignore this file, do you?

2020-10-19 08:59 UTC, in-a-paddy commented on docs/content/react-native/icon/_index.md
> +React Native ElementsのIconでは多数のアイコンを使用できますが、独自のアイコンを使いたい場合は、[こちらを](https://github.com/oblador/react-native-vector-icons#custom-fonts)参考にしてください。
```suggestion
React Native ElementsのIconでは多数のアイコンを使用できますが、独自のアイコンを使いたい場合は、[こちら](https://github.com/oblador/react-native-vector-icons#custom-fonts)を参考にしてください。
```

2020-10-19 08:59 UTC, in-a-paddy commented on docs/content/react-native/icon/_index.md
> +## SVGの取り扱いの難しさ
I want this document to be written for the project's app developers.

Now, it looks like to be written for the leaders not for the members.

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/CameraIcon.tsx
> +const GearIcon = ({color = '#9D8CB8', ...props}: SpecificIconType) => {
Filename is `CameraIcon.tsx`. Remove the icon name from variable name so that they can be easily reused.

```suggestion
const Icon = ({color = '#9D8CB8', ...props}: SpecificIconType) => {
```

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/CameraIcon.tsx
> +export default GearIcon;
```suggestion
export default Icon;
```

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/GearIcon.tsx
> +const GearIcon = ({color = '#9D8CB8', ...props}: SpecificIconType) => {
```suggestion
const Icon = ({color = '#9D8CB8', ...props}: SpecificIconType) => {
```

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/GearIcon.tsx
> +export default GearIcon;
```suggestion
export default Icon;
```

2020-10-19 08:59 UTC, in-a-paddy commented on package.json
> +    "generate-svgr": "svgr ./svg --out-dir src/generated/svg --template svgr-template.js --native --typescript --memo "
I don't want to put `svgr-template.js` in the root directory.

2020-10-19 08:59 UTC, in-a-paddy commented on package.json
> +    "react-native-svg": "~12.1.0",
Since it's not relevant to most projects, It's better to put the SVG icon samples in another repository.

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/index.tsx
> +import CameraIcon from './CameraIcon';
Filename should be `index.ts`

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/pages/HomeScreen.tsx
> +const styles = StyleSheet.create({
You don't have to apply the styles just yet.

`<Text style={styles.text}>` should be placed in `parts` and styles should be configured there, not in pages.

2020-10-19 08:59 UTC, in-a-paddy commented on package.json
> +    "@types/react-native-vector-icons": "~6.4.6",
I think there is no need to use `react-native-vector-icons` directly.

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/HomeIcon.tsx
> +type SpecificIconType = Omit<IconProps, 'name' | 'type'>;
Don't you have to define in every file?

2020-10-19 08:59 UTC, in-a-paddy commented on src/example/components/basics/CameraIcon.tsx
> +export default GearIcon;
Or, inline the variable.

2020-10-28 07:10 UTC, Takumon commented on .eslintignore
> +src/generated/*
I added

2020-10-29 05:27 UTC, Takumon commented on src/example/components/pages/HomeScreen.tsx
> +const styles = StyleSheet.create({
I moved the Text to parts.

2020-10-29 05:27 UTC, Takumon commented on src/example/components/basics/index.tsx
> +import CameraIcon from './CameraIcon';
Fix typo

2020-10-29 05:28 UTC, Takumon commented on src/example/components/basics/CameraIcon.tsx
> +const GearIcon = ({color = '#9D8CB8', ...props}: SpecificIconType) => {
I fixed this issue in all icon components.

2020-10-29 05:29 UTC, Takumon commented on docs/content/react-native/icon/_index.md
> +## SVGの取り扱いの難しさ
I removed description about svg which is no need for project's app developers.

2020-10-29 05:30 UTC, Takumon commented on .eslintignore
> +src/generated/*
I added `.eslintrc.js`

2020-10-29 05:32 UTC, Takumon commented on .eslintignore
> +svgr-template.js
You're right. I removed it  and fix lint errors of it.

2020-10-29 05:32 UTC, Takumon commented on docs/content/react-native/icon/_index.md
> +React Native ElementsのIconでは多数のアイコンを使用できますが、独自のアイコンを使いたい場合は、[こちらを](https://github.com/oblador/react-native-vector-icons#custom-fonts)参考にしてください。
I fixed it

2020-10-29 05:36 UTC, Takumon commented on src/example/components/basics/HomeIcon.tsx
> +type SpecificIconType = Omit<IconProps, 'name' | 'type'>;
I moved the type definition to `Constants.ts`.

2020-10-29 05:56 UTC, Takumon commented on package.json
> +    "@types/react-native-vector-icons": "~6.4.6",
I removed it.

2020-10-29 05:58 UTC, Takumon commented on package.json
> +    "react-native-svg": "~12.1.0",
Gat it. I removed all code related to SVG icon.

2020-10-29 06:19 UTC, Takumon commented on src/example/components/basics/CameraIcon.tsx
> +import {Icon as RNEIcon, IconProps} from 'react-native-elements';
fixed it

2020-10-29 06:19 UTC, Takumon commented on src/example/components/basics/GearIcon.tsx
> +import {Icon as RNEIcon, IconProps} from 'react-native-elements';
fixed it

2020-10-29 06:41 UTC, Takumon commented on src/example/components/basics/CameraIcon.tsx
> +import {Icon as RNEIcon, IconProps} from 'react-native-elements';
fixed it

2020-10-29 06:41 UTC, Takumon commented on src/example/components/basics/GearIcon.tsx
> +import {Icon as RNEIcon, IconProps} from 'react-native-elements';
fixed it

2020-11-04 20:14 UTC, in-a-paddy requested changes

2020-11-04 20:14 UTC, in-a-paddy commented on .eslintignore
> +.eslintrc.js
Do you need this?

2020-11-04 20:14 UTC, in-a-paddy commented on src/example/components/basics/HomeIcon.tsx
> +type SpecificIconType = Omit<IconProps, 'name' | 'type'>;
Still here

2020-11-04 20:14 UTC, in-a-paddy commented on src/example/components/Constants.ts
> +export type SpecificIconType = Omit<IconProps, 'name' | 'type'>;
Moving to `basics` and rename to `SpecificIconType.ts` is better, I think.

2020-11-04 20:15 UTC, in-a-paddy commented
We should update `REAME.md`

2020-11-04 20:17 UTC, in-a-paddy commented on .eslintignore
> +src/generated/*
Where?

2020-11-05 06:43 UTC, Takumon commented on src/example/components/basics/HomeIcon.tsx
> +type SpecificIconType = Omit<IconProps, 'name' | 'type'>;
I fixed the issue in all icon files.

2020-11-05 06:49 UTC, Takumon commented on .eslintignore
> +.eslintrc.js
I think so too.
I removed this file.

2020-11-05 06:50 UTC, Takumon commented on src/example/components/Constants.ts
> +export type SpecificIconType = Omit<IconProps, 'name' | 'type'>;
That's right.
I did so.

2020-11-05 19:19 UTC, in-a-paddy requested changes

2020-11-05 19:19 UTC, in-a-paddy commented on package.json
> +    "@types/react-native-vector-icons": "~6.4.6",
???

2020-11-05 22:48 UTC, in-a-paddy approved these changes

2020-11-05 22:48 UTC, merged