Add react-native-cli Confirmation and uninstall procedure
ws-4020/rn-spoiler pull request #35
Opened 2020-11-26 07:52 UTC by OshitaTatsuya

## 💣 BREAKING CHANGE 💣

- 破壊的な変更を箇条書きで記載してください
- 変更内容と変更理由を、わかりやすく記載してください
- なければ、このセクションを削除してください

## やったこと

- [ ] やったことをチェック付きの箇条書きで記載してください
- [x] README.mdへ実行環境にreact-native-cliがインストールされていないかを確認し、インストールされている場合、アンインストールする旨を追記。

## やっていないこと

- やっていないこと（やる予定がないこと）を箇条書きで記載してください
特になし

## 動作確認

- [x] vscode内で、編集結果のプレビュー表示を行い確認済。

## デバイス

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [x] Windows
  - [x] ブラウザ (Chrome)

## その他（レビュアーへの申し送り事項、懸念点など）
本対応初の修正の為、README.mdの記載要領やブランチ名／プルリクエスト等について、
不備がないかご確認頂ければと思います。

2020-11-27 01:39 UTC, Takumon reviewed
ちょっとだけ、見ました。

2020-11-27 01:39 UTC, Takumon commented on README.md
> +・実行例
`（Windowsの場合）` などの注釈を入れたほうがいい気がします。

2020-11-27 01:55 UTC, in-a-paddy requested changes

2020-11-27 01:55 UTC, in-a-paddy commented on README.md
> +```
```suggestion
次のように結果が表示されます。ここに `react-native-cli` が含まれている場合は、 **必ず** アンインストールしてください。 `npm uninstall -g react-native-cli` でアンインストールできます。

> +-- expo-cli@3.28.5
> +-- npm@6.14.8
> +-- react-native-cli@2.0.1
>  `-- yarn@1.22.10
```

2020-11-27 01:55 UTC, in-a-paddy commented on README.md
> +次のものが実行環境内にインストールされていると正常に動作しない為、アンインストールを実施して下さい。
```suggestion
`react-native-cli` がグローバルにインストールされていると、テンプレートからの新規プロジェクトの作成に失敗します。
```

2020-11-27 01:55 UTC, in-a-paddy commented on README.md
> +※本コマンドを実行するとアンインストールが開始されます
```suggestion
```

2020-11-27 01:55 UTC, in-a-paddy commented on README.md
> +実行環境内のインストール物の確認は次のコマンドを実行して確認してください。
```suggestion
グローバルにインストールされているパッケージは `npm ls -g --depth=0` で確認することができます。
```

2020-11-27 01:57 UTC, in-a-paddy commented
> なければ、このセクションを削除してください

Pull Requstの本文から、「💣 BREAKING CHANGE 💣」のセクションを削除しておいてほしいです。

2020-11-27 02:00 UTC, in-a-paddy commented
チェックボックスがあると、プルリクエストの一覧で「全部で何個タスクがあって、何個終わったのか」が見えるようになります。

>  やったことをチェック付きの箇条書きで記載してください
のようにチェックを付けるつもりがないものを残していると、「タスク終わってなくね？」となるので、整理してもらいたいです。
（というか、テンプレートにもともとあるチェックリストは消してしまって問題ないです。）

2020-11-27 02:01 UTC, in-a-paddy commented
文面が固すぎるのが気になります。チーム内のレビュー依頼として、↓の文面はさすがに固すぎると感じます。もっとフランクにお願いしたいです。

> 本対応初の修正の為、README.mdの記載要領やブランチ名／プルリクエスト等について、
> 不備がないかご確認頂ければと思います。

2020-11-28 06:03 UTC, in-a-paddy commented
「やっていないこと」はやる予定がないことだと思うので、チェックボックスにしなくて大丈夫です。

2020-11-28 06:17 UTC, in-a-paddy requested changes

2020-11-28 06:17 UTC, in-a-paddy commented on README.md
> +
```suggestion
グローバルにインストールされているパッケージは `npm ls -g --depth=0` で確認することができます。実行結果に `react-native-cli` が含まれている場合は、 **必ず** アンインストールしてください。 `npm uninstall -g react-native-cli` でアンインストールできます。
```

2020-11-28 06:17 UTC, in-a-paddy commented on README.md
> +
パス部分だけがWindowsに依存していて、そのためだけに「Windowsの場合」という注釈が入っていますが、ほぼ無意味かなぁ、と。↓ のような内容で充分では？

```suggestion
> npm ls -g --depth=0

+-- expo-cli@3.28.5
+-- npm@6.14.8
+-- react-native-cli@2.0.1
`-- yarn@1.22.10
```

2020-12-02 08:03 UTC, in-a-paddy approved these changes

2020-12-02 08:03 UTC, merged