🌱:rn-spoilerをテンプレートとしたアプリ（内容は学習コンテンツ）を構築するスクリプトの作成
ws-4020/rn-spoiler pull request #65
Opened 2021-05-25 02:47 UTC by creature-water-valley

## ✅ What's done

- [ ] rn-spoilerをテンプレートとしたアプリ（内容は学習コンテンツ）を構築するスクリプトの作成
  - [ ] アプリは`generated`ディレクトリに作成
  - [ ] `example/hands-on/patches`に格納しているパッチファイルを適用して学習コンテンツをアプリに反映
  - [ ] スクリプトで構築するのは、`npm run ios/android`さえ手動なりで実行すればアプリが立ち上がる所まで
- [ ] `generated`ディレクトリは`.gitignore`に追加して`rn-spoiler`のGit管理からは除外

## ⏸ What's not done

- 作成したスクリプトは、Github Actionsなどで何かをトリガーに自動実行するようにはしていません

---

## Tests

- [ ] 学習コンテンツの各ページを打鍵

## Devices

- [] Expo Go
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

なし

2021-05-26 01:48 UTC, in-a-paddy requested changes

2021-05-26 01:48 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.sh
> +EXECUTABLE_SCRIPT_DIR=$(cd $(dirname $0); pwd)
ここでROOT_DIRを取っちゃった方が良いと思う。`git rev-parse`使うのが個人的には好み（ディレクトリ移動してもあまり影響受けないから）
https://github.com/team-kaba/selidor/blob/master/.ci/scripts/env.sh#L8

2021-05-26 01:48 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.sh
> +cd $WORK_DIR
`WORK_DIR`は先に定義しておいた方が良い気がする。
こんな感じとか？

```suggestion
WORK_DIR="${ROOT_DIR}/generated"
mkdir -p "${WORK_DIR}"
cd "$WORK_DIR"
```

2021-05-26 01:48 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.sh
> +RN_SPOILER_DIR=$(pwd)
ROOT_DIRを取っておけば、この辺のcdはいらなくなると思う。

2021-05-26 01:48 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.sh
> +cd $EXECUTABLE_SCRIPT_DIR
ROOT_DIRを取っておけば、この辺のcdはいらなくなると思う。

2021-05-27 04:32 UTC, tani-takanori reviewed
実行権限ついてない？？

2021-05-27 05:03 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.sh
> +npx react-native init --template https://github.com/ws-4020/rn-spoiler.git $APP_NAME
set -e されてるから、失敗したらスクリプト落ちるんじゃない？

2021-05-27 05:07 UTC, in-a-paddy commented
> 実行権限ついてない？？

実行権限はつけておいてほしいな。けど、Windowsで編集して実行権限が吹き飛ばされるのを何度も経験したから、実行する側（GitHub Actionsとか）は、実行権限ついてない前提で作った方が良いと思う。

2021-05-27 06:20 UTC, creature-water-valley commented on example/hands-on/create-hands-on-app.sh
> +EXECUTABLE_SCRIPT_DIR=$(cd $(dirname $0); pwd)
ここでプロジェクトルートを取得するようにしましたー

2021-05-27 06:21 UTC, creature-water-valley commented on example/hands-on/create-hands-on-app.sh
> +cd $WORK_DIR
先に定義するようにしましたー

2021-05-27 06:22 UTC, creature-water-valley commented on example/hands-on/create-hands-on-app.sh
> +RN_SPOILER_DIR=$(pwd)
削除しましたー

2021-05-27 06:22 UTC, creature-water-valley commented on example/hands-on/create-hands-on-app.sh
> +cd $EXECUTABLE_SCRIPT_DIR
削除しましたー

2021-05-27 06:23 UTC, creature-water-valley commented
くせで`bash xxxx.sh`で実行してたので、権限がないのに気づきませんでしたー
実行権限つけました！

2021-05-27 06:31 UTC, tani-takanori approved these changes

2021-05-27 08:34 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.sh
> +npx react-native init --template https://github.com/ws-4020/rn-spoiler.git $APP_NAME
現状、npm固定にしておきたい。（`package-lock.json`前提にもなってるし）

```suggestion
npx react-native init --npm --template https://github.com/ws-4020/rn-spoiler.git $APP_NAME
```

2021-05-27 10:45 UTC, in-a-paddy approved these changes

2021-05-27 10:45 UTC, merged