✅: 全部通し完了のよるパッチファイルの更新
ws-4020/rn-spoiler pull request #68
Opened 2021-06-18 09:11 UTC by nagano-ryo

## ✅ What's done

- [x] 全部通し完了のよるパッチファイルの更新（画面の実装まで）

## Other (messages to reviewers, concerns, etc.)

なし

2021-06-18 09:15 UTC, creature-water-valley commented on example/hands-on/patches/06-login-screen.patch
> ++++ b/package-lock.json
`package-lock.json`が入っちゃってますね。

2021-06-18 09:28 UTC, nagano-ryo commented on example/hands-on/patches/06-login-screen.patch
> ++++ b/package-lock.json
package-lock.jsonの差分を削除
e9bfcef57cbf32af5a0b04a285b38c0f3ae18482

2021-06-22 02:41 UTC, creature-water-valley commented
logoのdiffがちゃんと取れてないのでエラーになってますね。
バイナリのdiffは、`git diff --binary`でとらないとダメみたいです。

2021-06-22 02:49 UTC, creature-water-valley commented
warningがちょこちょこ出てるようです。

`trailing whitespace.`
`new blank line at EOF.`

2021-06-22 02:52 UTC, creature-water-valley commented
PRの説明に、テスト実施内容が入ってないですが動作確認はしてないですかね？
パッチファイルを更新した際は、
* `create-hands-on-app.sh`を実行してアプリ作成
* アプリを起動して簡単に打鍵

くらいは実施した方が良いと思います。

2021-06-23 06:29 UTC, in-a-paddy requested changes

2021-06-23 06:29 UTC, in-a-paddy commented on example/hands-on/patches/01-welcome.patch
> ++package com.todo_app_0617.generated;
パッケージ名って、ここで固定値で指定していいのかな？

2021-06-23 06:30 UTC, tani-takanori commented on example/hands-on/patches/01-welcome.patch
> ++package com.todo_app_0617.generated;
この子AndroidEmulatorとかで動かせば勝手に作成される子じゃないかな？

2021-06-23 06:35 UTC, in-a-paddy commented on example/hands-on/patches/01-welcome.patch
> ++package com.todo_app_0617.generated;
そだよ

2021-06-23 07:06 UTC, nagano-ryo commented on example/hands-on/patches/01-welcome.patch
> ++package com.todo_app_0617.generated;
`android/app/src/main/java/com/todo_app_0617/generated/BasePackageList.java
`
そもそも上記ファイルがパッチファイルの中に含まれているのがおかしいと思っているのですが、認識あっていますか？（前回の水谷さんパッチファイルには含まれていなかったため）

2021-06-23 07:21 UTC, in-a-paddy commented on example/hands-on/patches/01-welcome.patch
> ++package com.todo_app_0617.generated;
ん～、おかしいというわけではないです。SantokuAppでは入れてます。
ここにパッケージ名が固定値になっているファイルがあったところで何の役にも立たないので、入れる必要がないという意味であれば同意です。

2021-06-23 08:26 UTC, nagano-ryo commented on example/hands-on/patches/01-welcome.patch
> ++package com.todo_app_0617.generated;
パッチファイルに入れる必要がないので含めないように修正します。

2021-06-25 07:04 UTC, in-a-paddy requested changes

2021-06-25 07:04 UTC, in-a-paddy commented on example/hands-on/patches/02-stack-navigation.patch
> +@@ -1,12 +1,46 @@
```suggestion
@@ -1,12 +1,45 @@
```

2021-06-25 09:10 UTC, creature-water-valley approved these changes

2021-06-25 09:56 UTC, tani-takanori approved these changes

2021-06-28 02:18 UTC, in-a-paddy approved these changes

2021-06-28 02:18 UTC, merged