Improvement create hands on app sh
ws-4020/rn-spoiler pull request #70
Opened 2021-07-02 00:56 UTC by nagano-ryo

## 💣 BREAKING CHANGES 💣

- 破壊的な変更を箇条書きで記載してください
- 変更内容と変更理由を、わかりやすく記載してください
- なければ、このセクション（先頭行から「## ✅ What's done」の前の行まで）を削除してください

## ✅ What's done

- [ ] やったことをチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

## ⏸ What's not done

- JSを実行するとgitコマンド時に以下のエラーが発生する（Windowsのコマンドプロンプト）
  - fatal: unable to write new_index file
  - fatal: couldn't set 'refs/heads/master'

---

## Tests

- [ ] 実施した動作確認の内容をチェック付きの箇条書きで記載してください
- [ ] 作業着手前に列挙して TODO リストのようにも使用できます
- [ ] やり終わったらチェックを付けてください

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ] Android
  - [ ] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

- JSの実行方法
  - プロジェクトをカレントディレクトリにして、以下のコマンドを実行
    `npm run create-hands-on-app`

2021-07-02 08:56 UTC, in-a-paddy requested changes

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +const appName = program.args[0] === undefined ? "HandsOnApp" : program.args[0];
これだと動かないのかな？
```suggestion
const appName = program.args[0] ?? "HandsOnApp";
```

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    '-b, --backend-ipadress <value>',
```suggestion
    '-b, --backend-ip-adress <value>',
```

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +  return fileName.split("-")[0] -0;
暗黙の型変換って、普通に使いますか？

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +execSyncCmd(`cd ${generetedDir} && npx react-native init --npm --template https://github.com/ws-4020/rn-spoiler.git ${appName}`);
実行時ディレクトリは引数で渡せませんか？

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    0
これって必須なんです？これだと、一つもパッチファイルを適用しない、ということができないのではないかと
設定されていなかったら`undefined`とかの方が良いと思います。

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +const appDir = `${__dirname}/generated/${appName}`;
この方が良いのでは？
```suggestion
const appDir = `${generetedDir}/${appName}`;
```

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +if (fs.existsSync(appDir)) {
ここが`true`になるケースって、消してしまっても大丈夫ですか？

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +  if (0 === options.skipPatchFileNum || options.skipPatchFileNum > pathFileNum) {
この場合は不等号は「<」でそろえたいです。読みにくいな、と。
```suggestion
  if (0 === options.skipPatchFileNum || pathFileNum < options.skipPatchFileNum) {
```

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    0
こういう仕様になってるってことですかね？
* `-s 0` → 全部適用される
* `-s 1` → 一つも適用されない

ちょっと直感的じゃないな、と。

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    let res = fs.readFileSync(backendConfigTs);
ファイルを一括でメモリに乗せるのは避けた方が良いです。

2021-07-02 08:56 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +function execSyncCmd(cmd) {
これが少しは参考になるかもしれないです。
https://github.com/ws-4020/mobile-app-crib-notes/blob/master/SantokuApp/.script/internals/task-executor.js

2021-07-02 09:03 UTC, in-a-paddy requested changes

2021-07-02 09:03 UTC, in-a-paddy commented on example/hands-on/patches/22-generate-api-client.patch
> ++export const config = new Configuration({basePath: 'http://LOCALHOST:9080/api'});
もうちょっとマーカーを入れた方が良いんじゃないかなぁ、と。

2021-07-02 09:03 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    res = res.toString().replace("LOCALHOST", options.backendIpadress);
これって、ファイル内で複数個`LOCALHOST`が出てきてたらどうなります？？

2021-07-05 00:41 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +  return fileName.split("-")[0] -0;
暗黙の型変換していた箇所をparseIntに修正
1b55c3c4749267e8f4b269acd42421138f2870a6

2021-07-05 00:47 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +if (fs.existsSync(appDir)) {
すでにアプリが存在した場合、アプリを削除する挙動については<https://github.com/ws-4020/rn-spoiler/blob/master/example/hands-on/create-hands-on-app.sh>にあわせてあります。

アプリが存在した場合は、何もせず処理を終了する、などが良いでしょうか？

2021-07-05 02:13 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +if (fs.existsSync(appDir)) {
勘違いでしたm(_ _)m
なぜか、`generated`を消していると思っていたっぽい

2021-07-05 02:43 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    let res = fs.readFileSync(backendConfigTs);
読み込んだファイルの内容をメモリに乗せないように修正
77f196e7228ebc01b394145ccbd2ac92b66cc0b9

2021-07-05 02:56 UTC, nagano-ryo commented on example/hands-on/patches/22-generate-api-client.patch
> ++export const config = new Configuration({basePath: 'http://LOCALHOST:9080/api'});
置換対象のsrc/backend/config.tsのバックエンド接続先IPアドレスにマーカーを追加
f26ddcf6087677f6418a9d377cceee55273a21b1

2021-07-05 02:57 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    res = res.toString().replace("LOCALHOST", options.backendIpadress);
ファイル内に複数置換対象文字列があった場合、すべて置換できるように修正
f26ddcf6087677f6418a9d377cceee55273a21b1

2021-07-05 03:01 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    let res = fs.readFileSync(backendConfigTs);
`fs.readFileSync`って一括で全部読み込むのかと思っていたのですが、違いますか？

2021-07-05 04:20 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    0
--skip-patch-file-numオプションのデフォルト値をundefinedに変更し、パッチ適用条件を修正
324f1d4eeef2b28b395109351f952edfc8542429

2021-07-05 04:47 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    0
これ、`undefined`ってわざわざ明記しないといけないですか？それとも、あえて書いている感じですかね？

2021-07-05 04:52 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    0
`undefined`は指定しなくても問題ありません。（指定してもしなくても同じ挙動）
今回は明示的に指定したのですが、削除したほうが良いですか？

2021-07-05 04:54 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    0
書いた方が良いですか？

2021-07-05 05:05 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    0
オプションが未指定の場合は、`undefined`になるということを明示的に示したほうが分かり易いと思うので、`undefined`を記載したほうが良いと考えています。

2021-07-05 05:20 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    0
了解です。であれば大丈夫です（他の人のレビューに任せます）。

参考までに、書かなくていいんじゃないかと私が思った理由をあげておきます。
* 他の関数呼び出しでは、引数に明示的に`undefined`を渡すわけではなく省略している
* Commander.jsのサンプルでも、引数に`undefined`を渡している例はない
* 一般的に、JavaScriptの引数には明示的に`undefined`を渡すよりも省略するケースが多く、省略時は`undefined`もしくは関数宣言で定義されたデフォルト値が採用されるというのは一般的な知識
  * ちなみに、明示的に`undefined`を渡すと、関数宣言で定義されたデフォルト値が利用されます

2021-07-05 05:57 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +execSyncCmd(`cd ${generetedDir} && npx react-native init --npm --template https://github.com/ws-4020/rn-spoiler.git ${appName}`);
コマンド実行ディレクトリを引数で指定するように修正
cc92d71a9176469bc2de646da4330e5861938fa9

2021-07-05 05:58 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +function execSyncCmd(cmd) {
コマンド実行をexecSync()からspawn()を利用するように修正
cc92d71a9176469bc2de646da4330e5861938fa9

2021-07-05 07:33 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    let res = fs.readFileSync(backendConfigTs);
ファイルの置換処理にてfs.readFileSync()でファイル内容を一括で読み込んでいる理由を追記
be0cae47233654b6fb4278512ea59d23861e3f76

2021-07-05 08:43 UTC, in-a-paddy commented on package.json
> +    "create-hands-on-app": "node example/hands-on/create-hands-on-app.js"
あとでいくつかできる可能性を考えて、`create-app:*`って感じで指定できるようにしておくと、稀に便利なことがあります。

```suggestion
    "create-app:hands-on": "node example/hands-on/create-hands-on-app.js"
```

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    // execute(`cd ${appDir} && git init && git add . && git commit -m "initial commit"`);
この辺のコメントって、情報増えてますか？

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> + * 第一引数：アプリ名(Optional. デフォルト値:HandsOnApp)
コメントじゃなく、`program.help`とかで書いた方が良い気がする。

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    const appName = program.args[0] ?? "HandsOnApp";
`program.argument` でやった方が良いのかもな、と。

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +      reject(error);
あれ、標準エラー出力に吐かれたらrejectして大丈夫なんだっけ？

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `npx pod-install`);
Windowsだと失敗しそうな気がするんですが、うまくいきました？

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +        // execute(`cd ${appDir} && git apply ../../patches/${patchFileName} && git add . && git commit -m "apply ${patchFileName}."`);
このコメントって何の意味がありますか？

2021-07-06 00:39 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `git commit -m "update src/backend/config.ts"`);
普段から、コミットメッセージにも気を使ってあげてもらいたいです。バックエンドAPIのIPアドレスを設定しているんだと思うので、そんな感じのメッセージにしておいた方が良いような。

2021-07-06 02:14 UTC, creature-water-valley commented
`package-lock.json`はgit管理しないですか？

2021-07-06 02:14 UTC, creature-water-valley commented
`node_modules`は`.gitignore`に足してもらえるとありがたいです。

2021-07-06 02:17 UTC, creature-water-valley commented
パッチファイルを適用する際に、↓の警告が出ています。

```
[master caf2ee7] apply 13-logo.patch.
 6 files changed, 32 insertions(+)
 create mode 100644 src/@types/image.d.ts
 create mode 100644 src/assets/logo.png
 create mode 100644 src/components/basics/image/Logo.tsx
 create mode 100644 src/components/basics/image/index.ts

../../patches/22-generate-api-client.patch:86: trailing whitespace.
 *
../../patches/22-generate-api-client.patch:121: trailing whitespace.
 *
../../patches/22-generate-api-client.patch:126: trailing whitespace.
     * 登録しているToDoを削除する。
../../patches/22-generate-api-client.patch:149: trailing whitespace.
     * 登録しているToDoを削除する。
../../patches/22-generate-api-client.patch:157: trailing whitespace.
     * 登録しているToDoを全て取得する。
```

2021-07-06 02:18 UTC, creature-water-valley commented
`create-hands-on-app.sh`はもういらないような？

2021-07-06 02:23 UTC, creature-water-valley commented
`config.ts`で指定しているipがundefinedになってます。

```
export const config = new Configuration({basePath: 'http://undefined:9080/api', middleware: [waitResponse]});
```

2021-07-06 02:36 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    // execute(`cd ${appDir} && git init && git add . && git commit -m "initial commit"`);
不要なコメントを削除
e4d241675356013bb9e9906177a58950b38c6463
e4d241675356013bb9e9906177a58950b38c6463

2021-07-06 02:38 UTC, creature-water-valley commented on example/hands-on/create-hands-on-app.js
> +    const generetedDir = `${__dirname}/generated`;
`generetedDir` → `generatedDir`

2021-07-06 02:38 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +        // execute(`cd ${appDir} && git apply ../../patches/${patchFileName} && git add . && git commit -m "apply ${patchFileName}."`);
不要なコメントを削除
e4d241675356013bb9e9906177a58950b38c6463
e4d241675356013bb9e9906177a58950b38c6463

2021-07-06 02:47 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `git commit -m "update src/backend/config.ts"`);
バックエンド接続先IPアドレスの書き換えを行った際のgit commitのメッセージを修正
625cd5161b6655a12a48e496eaee20aa0819cf35

2021-07-06 02:50 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    const generetedDir = `${__dirname}/generated`;
typoを修正　`generetedDir` → `generatedDir`
99402521c0eb381713e3682c7563c06f6e19d318

2021-07-07 05:00 UTC, nagano-ryo commented
> `package-lock.json`はgit管理しないですか？
package-lock.jsonを管理対象に追加しました
86b5b9e6937dd2aaaba4eec337c83c563b05acc1

2021-07-07 05:01 UTC, nagano-ryo commented
> `node_modules`は`.gitignore`に足してもらえるとありがたいです。



> `node_modules`は`.gitignore`に足してもらえるとありがたいです。

2021-07-07 05:02 UTC, nagano-ryo commented
> `node_modules`は`.gitignore`に足してもらえるとありがたいです。

上記対応しました
86b5b9e6937dd2aaaba4eec337c83c563b05acc1

2021-07-07 05:05 UTC, nagano-ryo commented
> `create-hands-on-app.sh`はもういらないような？
上記削除しました。
2f88f12b5bfdaa21e175fbbd8c05281b6e3069cf

2021-07-07 05:06 UTC, nagano-ryo commented
> パッチファイルを適用する際に、↓の警告が出ています。
> 
> ```
> [master caf2ee7] apply 13-logo.patch.
>  6 files changed, 32 insertions(+)
>  create mode 100644 src/@types/image.d.ts
>  create mode 100644 src/assets/logo.png
>  create mode 100644 src/components/basics/image/Logo.tsx
>  create mode 100644 src/components/basics/image/index.ts
> 
> ../../patches/22-generate-api-client.patch:86: trailing whitespace.
>  *
> ../../patches/22-generate-api-client.patch:121: trailing whitespace.
>  *
> ../../patches/22-generate-api-client.patch:126: trailing whitespace.
>      * 登録しているToDoを削除する。
> ../../patches/22-generate-api-client.patch:149: trailing whitespace.
>      * 登録しているToDoを削除する。
> ../../patches/22-generate-api-client.patch:157: trailing whitespace.
>      * 登録しているToDoを全て取得する。
> ```

上記のエラーはopen-api-generatorが生成したソースに対しての指摘なので対応不要と考えます。

2021-07-07 05:41 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +      reject(error);
`proc.stderr.onのerror`イベントは以下のケースで発生する認識です。そのためrejectしています。
一方、標準エラー出力は`proc.stderr.onのdata`イベントで出力しています。
- プロセスを生成できなかった
- プロセスを強制終了できなかった
- 子プロセスへのメッセージの送信に失敗

2021-07-07 05:45 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `npx pod-install`);
`npm install --legacy-peer-deps`は問題ありませんが、`npx pod-install`は以下の標準エラーが出力されます。
`CocoaPods is only supported on darwin machines`
上記が出力されても処理は続行するため、今の仕様で問題ないと考えています。
（Windowsユーザーは赤字のメッセージに気付き、問題ないことに気付けると思っています。）

2021-07-07 06:25 UTC, tani-takanori commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `npx pod-install`);
https://github.com/expo/expo-cli/blob/master/packages/pod-install/src/index.ts#L37-L40

just `return`

2021-07-07 06:32 UTC, tani-takanori commented on example/hands-on/create-hands-on-app.js
> +    const appName = program.args[0] ?? "HandsOnApp";
@nagano-ryo 
https://github.com/expo/expo-cli/blob/master/packages/pod-install/src/index.ts#L16
https://github.com/expo/expo-cli/blob/master/packages/pod-install/src/index.ts#L21

2021-07-07 06:59 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> + * 第一引数：アプリ名(Optional. デフォルト値:HandsOnApp)
第一引数のアプリ名をprogram.argumentにて指定
7f6de2ae17f4535b8bd316f41ee719ad6f8f9a60

2021-07-07 07:00 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +    const appName = program.args[0] ?? "HandsOnApp";
第一引数のアプリ名をprogram.argumentにて指定
7f6de2ae17f4535b8bd316f41ee719ad6f8f9a60

2021-07-07 08:08 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    // execute(`cd ${appDir} && git init && git add . && git commit -m "initial commit"`);
```
    // git init
    // git add .
    // git commit -m "initial commit"
```

これって何を伝えたいコメントですか？？

2021-07-07 08:11 UTC, in-a-paddy commented
> node_modulesは.gitignoreに足してもらえるとありがたいです。

これって、どこの`node_modules`を指してるんだろ？generatedの方はrn-spoilerから作られたときにgitignoreに入ってるべきだと思う。

2021-07-07 08:11 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +    // execute(`cd ${appDir} && git init && git add . && git commit -m "initial commit"`);
あぁ、別のコミットで消してるのかな。

2021-07-07 08:18 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +      reject(error);
了解です、勘違いしてたみたい。`stderr`だけハンドリングしているのはなんでです？

2021-07-07 08:18 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +      reject(error);
了解です、勘違いしてたみたい。ちなみに、`stderr`だけハンドリングしているのはなんでです？

2021-07-07 08:18 UTC, in-a-paddy commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `npx pod-install`);
おっけーです

2021-07-07 09:06 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +      await execute(appDir, `git commit -m "update src/backend/config.ts"`);
バックエンド接続先IPアドレスの英訳をBackend Server IP addressに修正
bb9507486311cf754ad0558e9c48acf4deee8157

2021-07-08 02:07 UTC, nagano-ryo commented
> > パッチファイルを適用する際に、↓の警告が出ています。
> > ```
> > [master caf2ee7] apply 13-logo.patch.
> >  6 files changed, 32 insertions(+)
> >  create mode 100644 src/@types/image.d.ts
> >  create mode 100644 src/assets/logo.png
> >  create mode 100644 src/components/basics/image/Logo.tsx
> >  create mode 100644 src/components/basics/image/index.ts
> > 
> > ../../patches/22-generate-api-client.patch:86: trailing whitespace.
> >  *
> > ../../patches/22-generate-api-client.patch:121: trailing whitespace.
> >  *
> > ../../patches/22-generate-api-client.patch:126: trailing whitespace.
> >      * 登録しているToDoを削除する。
> > ../../patches/22-generate-api-client.patch:149: trailing whitespace.
> >      * 登録しているToDoを削除する。
> > ../../patches/22-generate-api-client.patch:157: trailing whitespace.
> >      * 登録しているToDoを全て取得する。
> > ```
> 
> 上記のエラーはopen-api-generatorが生成したソースに対しての指摘なので対応不要と考えます。

git apply時にtrailing whitespaceの警告メッセージが出力されないように-–whitespace=nowarnを付与
8585cc834622424df032f017767280734a421ce2

2021-07-08 02:30 UTC, nagano-ryo commented on example/hands-on/create-hands-on-app.js
> +      reject(error);
`stderr`のハンドリングは削除漏れでした。
実装当初、標準エラー出力のハンドリング目的で`stderr`をハンドリングしていましたが、
標準エラー出力のハンドリングは`stderr`でなく`proc.stderr.onのdata`イベントであることに気付き修正しました。本来はそのタイミングで`stderr`のハンドリングを削除するべきでした。

725835ee657f83bec66d177cac55f57ae49bc690

2021-07-08 04:39 UTC, creature-water-valley approved these changes

2021-07-08 05:43 UTC, in-a-paddy approved these changes

2021-07-08 05:43 UTC, merged